### PR TITLE
Capability Configuration via COMPUTE_ENVIRONMENT variable.

### PR DESCRIPTION
**Pull request by michaelweber**
Option 1 for implementing individual capability configuration on a Chariot Compute vs. Local Compute level.

NOTE: Requires Backend to set `COMPUTE_ENVIRONMENT` to `chariot` in its environment.

### CODE REVIEW

**Comment by privateducky** [comment]
Thought about this one; I think our "capability runner" in this project should load a ``.env`` file (similar to the Chariot backend process) and in this config, a user can optionally override whatever default values we supply.

**Review by privateducky — CHANGES_REQUESTED** [review]
Thought about this one; I think our "capability runner" in this project should load a .env file (similar to the Chariot backend process) and in this config, a user can optionally override whatever default values we supply.

**Comment by michaelweber** [comment]
That's currently what happens when we run the command, we just use docker to pass in the .env file via the `--env-file` flag. Do we want to skip that part and add code to replace what docker does and explicitly load a .env file and pass that in instead?

**Comment by privateducky** [comment]
> That's currently what happens when we run the command, we just use docker to pass in the .env file via the `--env-file` flag. Do we want to skip that part and add code to replace what docker does and explicitly load a .env file and pass that in instead?

Where would a user adjust the .env file in our current flow?

**Comment by michaelweber** [comment]
Before using the CLI to execute the compute capability. There's a flag to explicitly specify the .env file to pass into the container. So like:

```
chariot compute --env /path/to/.env
```

Then any calls to `os.GetEnv` would use values from that `.env` file.  So all we need to do in the capability code is check with `os.GetEnv` and call it a day knowing it will have been overridden where necessary.

**Comment by privateducky** [comment]
> Before using the CLI to execute the compute capability. There's a flag to explicitly specify the .env file to pass into the container. So like:
> 
> ```
> chariot compute --env /path/to/.env
> ```
> 
> Then any calls to `os.GetEnv` would use values from that `.env` file. So all we need to do in the capability code is check with `os.GetEnv` and call it a day knowing it will have been overridden where necessary.

Awesome. I think this is a safe/simple way to handle this. Which puts the PR dance back closer to your initial version.

**Pull request closed without merging**
