### PR TITLE
fix asset key validation regex for assets with empty DNS values

### PR DESCRIPTION
**Pull request by praetorian-harry**
Related issue: https://github.com/praetorian-inc/chariot-ui/issues/740#issuecomment-2361860904

The current `Asset.Valid()` function has regex that fails if the asset key is empty where the `DNS` field is located. We currently support assets without requiring that `DNS` is non-empty, particularly from cloud integration, resulting in keys like `#asset##1.1.1.1`.

This PR updates our validation regex to allow such asset keys with empty `DNS` values to pass validation.

image

### CODE REVIEW

**Comment by noah-tutt-praetorian** [comment]
This is a bit tricky, I don't know that I actually want these assets to pass this regex (imply that users can create them)

**Comment by praetorian-harry** [comment]
@noah-tutt-praetorian got it. We currently use this validation to ensure that the supplied key is "valid" when we re-run jobs at the `/job` endpoint. I could instead update the logic there to be less strict about the keys that are allowed as input to the job re-run endpoint?

**Comment by noah-tutt-praetorian** [comment]
ahh, interesting

**Comment by noah-tutt-praetorian** [comment]
can we assume that if a key exists in the table, it's valid?

**Comment by praetorian-harry** [comment]
@noah-tutt-praetorian yes, I think that's a reasonable approach. I'll close this PR and write that instead :+1:

**Comment by praetorian-harry** [comment]
> I think it's also worth tracking down where this came from and fixing it from that angle too. Presumably there's a sensible DNS value we can provide instead (probably just the ip address)

@noah-tutt-praetorian I tracked down this specific case to a discovered EC2 instance and opened a PR that should fix it going forward: https://github.com/praetorian-inc/chariot-client/pull/92

**Pull request closed without merging**
